source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '12.0'

target 'Osmosis Example' do
  pod "Osmosis", :path => "../"
  pod 'AsyncSwift'
  
  # Testing pods
  pod 'Quick'
  pod 'Nimble'
end
