# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift
rvm:
- 2.2.2
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/Osmosis.xcworkspace -scheme Osmosis-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
